import os
import yaml

def index_skills(skills_dir):
    """
    Scans the skills directory and prints a summary of available skills.
    """
    print(f"--- Antigravity Skill Index ---")
    print(f"Scanning directory: {skills_dir}\n")

    found_skills = []

    if not os.path.exists(skills_dir):
        print(f"Error: Skills directory '{skills_dir}' does not exist.")
        return

    for item in os.listdir(skills_dir):
        item_path = os.path.join(skills_dir, item)
        if os.path.isdir(item_path):
            skill_md_path = os.path.join(item_path, "SKILL.md")
            if os.path.exists(skill_md_path):
                try:
                    with open(skill_md_path, 'r') as f:
                        # Simple parsing of YAML frontmatter
                        content = f.read()
                        if content.startswith("---"):
                            end_frontmatter = content.find("---", 3)
                            if end_frontmatter != -1:
                                frontmatter = content[3:end_frontmatter]
                                data = yaml.safe_load(frontmatter)
                                found_skills.append({
                                    "name": data.get("name", item),
                                    "description": data.get("description", "No description provided.")
                                })
                except Exception as e:
                    print(f"Warning: Failed to parse {item}: {e}")

    if not found_skills:
        print("No skills found.")
        return

    index_file_path = os.path.join(skills_dir, "index.md")
    
    try:
        with open(index_file_path, 'w') as f:
            f.write("# Antigravity Skill Index\n\n")
            f.write(f"This index is automatically generated by `skill-manager`. Last updated: {os.path.basename(skills_dir)}\n\n")
            
            for skill in found_skills:
                f.write(f"## [{skill['name']}](./{skill['name']}/SKILL.md)\n")
                f.write(f"{skill['description']}\n\n")
        
        print(f"Successfully generated index at: {index_file_path}")
        
        # Also print to console for immediate feedback
        print(f"--- Summary ---")
        for skill in found_skills:
            print(f"🔹 {skill['name']}")
    except Exception as e:
        print(f"Error writing index file: {e}")

if __name__ == "__main__":
    import sys
    # Default skills directory
    home = os.path.expanduser("~")
    skills_path = os.path.join(home, "Skills")
    
    if len(sys.argv) > 1:
        skills_path = sys.argv[1]
        
    index_skills(skills_path)
